---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by GIGABYTE.
--- DateTime: 2021/1/29 20:45
---

function ItemDataUtils:gameRootPath()
    if DataLink:useDataLink() then
        return "./editor_link/"
    else
        return "./editor/"
    end
end


function ItemDataUtils:delDir(path)
    if DataLink:useDataLink() then
        DataLink:delDir(path)
    else
        os.execute(string.format([[RD /S/Q "%s"]], path))
    end
end

function ItemDataUtils:delFile(path)
    if DataLink:useDataLink() then
        DataLink:delFile(path)
    else
        os.remove(path)
    end
end

function ItemDataUtils:del(path)
    if not DataLink:useDataLink() then
        VFS:del(path)
    end
end

return ItemDataUtils